export const searchDatas = [
  {
    keyword: ['스트레칭', '스트레', '스트'],
    results: [{id: 100}],
  },
  {
    keyword: [
      '목',
      '목 ',
      '목 아이솔레이션',
      '목 아이솔레이',
      '목 아이솔레',
      '목 아이솔',
      '목 아이',
      '목 아',

      '목아이솔레이션',
      '목아이솔레이',
      '목아이솔레',
      '목아이솔',
      '목아이',
    ],
    results: [{id: 101}],
  },
  {
    keyword: [
      '어깨',
      '어깨 ',
      '어깨 아이솔레이션',
      '어깨 아이솔레이',
      '어깨 아이솔레',
      '어깨 아이솔',
      '어깨 아이',
      '어깨 아',

      '어깨아이솔레이션',
      '어깨아이솔레이',
      '어깨아이솔레',
      '어깨아이솔',
      '어깨아이',
    ],
    results: [{id: 102}],
  },
  {
    keyword: [
      '가슴',
      '가슴 ',
      '가슴 아이솔레이션',
      '가슴 아이솔레이',
      '가슴 아이솔레',
      '가슴 아이솔',
      '가슴 아이',
      '가슴 아',

      '가슴아이솔레이션',
      '가슴아이솔레이',
      '가슴아이솔레',
      '가슴아이솔',
      '가슴아이',
    ],
    results: [{id: 103}],
  },
  {
    keyword: [
      '골반',
      '골반 ',
      '골반 아이솔레이션',
      '골반 아이솔레이',
      '골반 아이솔레',
      '골반 아이솔',
      '골반 아이',
      '골반 아',

      '골반아이솔레이션',
      '골반아이솔레이',
      '골반아이솔레',
      '골반아이솔',
      '골반아이',
    ],
    results: [{id: 104}],
  },
  {
    keyword: ['아이솔레이션', '아이솔레이', '아이솔레', '아이솔'],
    results: [{id: 101}, {id: 102}, {id: 103}, {id: 104}],
  },
  {
    keyword: ['팔 뻗기', '팔 뻗', '팔 ', '팔'],
    results: [{id: 105}],
  },
  {
    keyword: ['웨이브', '웨이'],
    results: [{id: 106}],
  },
  {
    keyword: [
      'HYPE BOY',
      'HYPE BO',
      'HYPE B',
      'HYPE ',
      'HYPEBOY',
      'HYPEBO',
      'HYPEB',
      'HYPE',

      'Hype Boy',
      'Hype Bo',
      'Hype B',
      'Hype ',
      'HypeBoy',
      'HypeBo',
      'Hype',

      'Hype boy',
      'Hype bo',
      'Hype b',
      'Hypeboy',
      'Hypebo',
      'Hypeb',

      'hype boy',
      'hype bo',
      'hype b',
      'hype ',
      'hypeboy',
      'hypebo',
      'hypeb',
      'hype',
    ],
    results: [{id: 800}],
  },
  {
    keyword: [
      'UNFORGIVEN',
      'UNFORGIVE',
      'UNFORGIV',
      'UNFORGI',
      'UNFORG',
      'UNFOR',

      'Unforgiven',
      'Unforgive',
      'Unforgiv',
      'Unforgi',
      'Unforg',
      'Unfor',

      'unforgiven',
      'unforgive',
      'unforgiv',
      'unforgi',
      'unforg',
      'unfor',
    ],
    results: [{id: 801}],
  },
  {
    keyword: [
      '파이팅 해야지',
      '파이팅 해야',
      '파이팅 해',
      '파이팅 ',
      '파이팅해야지',
      '파이팅해야',
      '파이팅해',
      '파이팅',
    ],
    results: [{id: 802}],
  },
  {
    keyword: [
      '꽃',
      'FLOWER',
      'FLOWE',
      'FLOW',

      'Flower',
      'Flowe',
      'Flow',

      'flower',
      'flowe',
      'flow',
    ],
    results: [{id: 803}],
  },
  {
    keyword: [
      'SEE TINH',
      'SEE TIN',
      'SEE TI',
      'SEE T',
      'SEE ',
      'SEETINH',
      'SEETIN',
      'SEETI',
      'SEET',

      'See Tinh',
      'See Tin',
      'See Ti',
      'See T',
      'See ',
      'SeeTinh',
      'SeeTin',
      'SeeTi',
      'SeeT',

      'See tinh',
      'See tin',
      'See ti',
      'See t',
      'Seetinh',
      'Seetin',
      'Seeti',
      'Seet',

      'see tinh',
      'see tin',
      'see ti',
      'see t',
      'see ',
      'seetinh',
      'seetin',
      'seeti',
      'seet',
    ],
    results: [{id: 804}],
  },
  {
    keyword: [
      'SE ACABO',
      'SE ACAB',
      'SE ACA',
      'SE AC',
      'SE A',
      'SEACABO',
      'SEACAB',
      'SEACA',
      'SEAC',
      'SEA',

      'Se Acabo',
      'Se Acab',
      'Se Aca',
      'Se Ac',
      'Se A',
      'SeAcabo',
      'SeAcab',
      'SeAca',
      'SeAc',
      'SeA',

      'Se acabo',
      'Se acab',
      'Se aca',
      'Se ac',
      'Se a',
      'Seacabo',
      'Seacab',
      'Seaca',
      'Seac',
      'Sea',

      'se acabo',
      'se acab',
      'se aca',
      'se ac',
      'se a',
      'seacabo',
      'seacab',
      'seaca',
      'seac',
      'sea',
    ],
    results: [{id: 805}],
  },
];
